name: Automatyczna aktualizacja wskaźników finansowych

on:
  # Uruchamia skrypt codziennie o 7:00 UTC (9:00 czasu polskiego letniego)
  schedule:
    - cron: '0 7 * * *'
  # Pozwala na ręczne uruchomienie z poziomu zakładki "Actions" na GitHubie
  workflow_dispatch:

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      # 1. Pobranie kodu z repozytorium
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Ustawienie środowiska Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # 3. Instalacja potrzebnych bibliotek
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      # 4. Uruchomienie skryptu aktualizującego
      - name: Run update script
        run: python update_script.py
        
      # 5. Zapisanie zmian i wysłanie ich do repozytorium
      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "📈 Automatyczna aktualizacja wskaźników"
          commit_user_name: GitHub Actions Bot
          commit_user_email: actions@github.com
          commit_author: GitHub Actions Bot <actions@github.com>
